export interface Disease {
  id: string;
  nameHi: string;
  nameEn: string;
  type: 'fungal' | 'pest' | 'viral' | 'bacterial';
  cropId: string;
  cropEmoji: string;
  cropHi: string;
  symptomsHi: string;
  symptomsEn: string;
  preventionHi: string;
  preventionEn: string;
  organicHi: string;
  organicEn: string;
  chemicalHi: string;
  chemicalEn: string;
}

export const DISEASES: Disease[] = [
  { id:'blast', nameHi:'ब्लास्ट (झोंका)', nameEn:'Rice Blast', type:'fungal', cropId:'rice', cropEmoji:'🌾', cropHi:'धान',
    symptomsHi:'पत्तियों पर हीरे के आकार के धब्बे, गर्दन टूटना, बालियाँ सफ़ेद',
    symptomsEn:'Diamond-shaped lesions on leaves, neck breaking, white panicles',
    preventionHi:'प्रतिरोधी किस्में लगाएं, नाइट्रोजन की मात्रा कम करें, खेत में पानी न रुकने दें',
    preventionEn:'Use resistant varieties, reduce nitrogen, avoid waterlogging',
    organicHi:'नीम तेल 3% का छिड़काव, ट्राइकोडर्मा विरिडी से बीज उपचार',
    organicEn:'Spray neem oil 3%, seed treatment with Trichoderma viride',
    chemicalHi:'ट्राइसाइक्लाज़ोल 75WP @ 0.6g/L या कार्बेन्डाज़िम 50WP @ 1g/L',
    chemicalEn:'Tricyclazole 75WP @ 0.6g/L or Carbendazim 50WP @ 1g/L' },
  { id:'bph', nameHi:'भूरा फुदका', nameEn:'Brown Planthopper', type:'pest', cropId:'rice', cropEmoji:'🌾', cropHi:'धान',
    symptomsHi:'पौधे पीले पड़ना, "हॉपर बर्न", जड़ के पास कीट झुंड',
    symptomsEn:'Plants yellowing, hopper burn, insect clusters near roots',
    preventionHi:'प्रतिरोधी किस्में, अत्यधिक नाइट्रोजन से बचें, खेत में रोशनी जाल लगाएं',
    preventionEn:'Resistant varieties, avoid excess nitrogen, use light traps',
    organicHi:'नीम आधारित कीटनाशक, मकड़ी और मेंढक जैसे प्राकृतिक शत्रुओं को बढ़ावा दें',
    organicEn:'Neem-based pesticides, encourage natural predators like spiders and frogs',
    chemicalHi:'इमिडाक्लोप्रिड 17.8SL @ 0.3ml/L या बुप्रोफेज़िन 25WP @ 1g/L',
    chemicalEn:'Imidacloprid 17.8SL @ 0.3ml/L or Buprofezin 25WP @ 1g/L' },
  { id:'sheath_blight', nameHi:'शीथ ब्लाइट', nameEn:'Sheath Blight', type:'fungal', cropId:'rice', cropEmoji:'🌾', cropHi:'धान',
    symptomsHi:'पत्ती के आवरण पर अनियमित हरे-भूरे धब्बे, बाद में सफ़ेद केंद्र',
    symptomsEn:'Irregular greenish-brown lesions on leaf sheath, later white center',
    preventionHi:'उचित दूरी पर रोपाई, नाइट्रोजन संतुलित मात्रा में दें',
    preventionEn:'Proper spacing during transplanting, balanced nitrogen application',
    organicHi:'ट्राइकोडर्मा हार्ज़ियानम @ 5g/L का छिड़काव',
    organicEn:'Spray Trichoderma harzianum @ 5g/L',
    chemicalHi:'हेक्साकोनाज़ोल 5EC @ 1ml/L या प्रोपिकोनाज़ोल 25EC @ 1ml/L',
    chemicalEn:'Hexaconazole 5EC @ 1ml/L or Propiconazole 25EC @ 1ml/L' },
  { id:'yellowrust', nameHi:'पीला रतुआ', nameEn:'Yellow Rust', type:'fungal', cropId:'wheat', cropEmoji:'🌿', cropHi:'गेहूँ',
    symptomsHi:'पत्तियों पर पीली धारियाँ, पीला पाउडर जैसा पदार्थ',
    symptomsEn:'Yellow stripes on leaves, yellow powder-like substance',
    preventionHi:'प्रतिरोधी किस्में (HD-2967), समय पर बुवाई, बीज उपचार',
    preventionEn:'Resistant varieties (HD-2967), timely sowing, seed treatment',
    organicHi:'लहसुन अर्क का छिड़काव, बायोएजेंट बेसिलस सबटिलिस का उपयोग',
    organicEn:'Garlic extract spray, use bioagent Bacillus subtilis',
    chemicalHi:'प्रोपिकोनाज़ोल 25EC @ 0.1% या टेबुकोनाज़ोल 25.9EC @ 1ml/L',
    chemicalEn:'Propiconazole 25EC @ 0.1% or Tebuconazole 25.9EC @ 1ml/L' },
  { id:'termite', nameHi:'दीमक', nameEn:'Termite', type:'pest', cropId:'wheat', cropEmoji:'🌿', cropHi:'गेहूँ',
    symptomsHi:'पौधे मुरझाना, जड़ें खाई हुई, पौधे आसानी से उखड़ जाते हैं',
    symptomsEn:'Plants wilting, roots eaten, plants easily uprooted',
    preventionHi:'बीज उपचार, खेत की गहरी जुताई, कच्ची खाद का उपयोग न करें',
    preventionEn:'Seed treatment, deep ploughing, avoid raw manure',
    organicHi:'नीम की खली @ 250kg/ha मिट्टी में मिलाएं',
    organicEn:'Mix neem cake @ 250kg/ha in soil',
    chemicalHi:'क्लोरपाइरीफॉस 20EC @ 2.5L/ha सिंचाई के साथ डालें',
    chemicalEn:'Apply Chlorpyrifos 20EC @ 2.5L/ha with irrigation' },
  { id:'loose_smut', nameHi:'अनावृत कंड', nameEn:'Loose Smut', type:'fungal', cropId:'wheat', cropEmoji:'🌿', cropHi:'गेहूँ',
    symptomsHi:'बालियाँ काले पाउडर से भर जाती हैं, दाने नहीं बनते',
    symptomsEn:'Ears filled with black powder, no grain formation',
    preventionHi:'प्रमाणित बीज का उपयोग, बीज उपचार अनिवार्य',
    preventionEn:'Use certified seed, seed treatment mandatory',
    organicHi:'गर्म पानी उपचार (52°C, 10 मिनट) से बीज उपचार',
    organicEn:'Hot water treatment (52°C, 10 min) for seed treatment',
    chemicalHi:'कार्बोक्सिन 75WP @ 2.5g/kg बीज से उपचार',
    chemicalEn:'Seed treatment with Carboxin 75WP @ 2.5g/kg seed' },
  { id:'bollworm', nameHi:'बॉलवर्म (सुंडी)', nameEn:'Bollworm', type:'pest', cropId:'cotton', cropEmoji:'🤍', cropHi:'कपास',
    symptomsHi:'टिंडे में छेद, कच्चे टिंडे गिरना, अंदर लार्वा दिखना',
    symptomsEn:'Holes in bolls, unripe bolls falling, larvae visible inside',
    preventionHi:'Bt कपास, फेरोमोन ट्रैप, समय पर बुवाई',
    preventionEn:'Bt cotton, pheromone traps, timely sowing',
    organicHi:'NPV (न्यूक्लियर पॉलीहेड्रोसिस वायरस) @ 250 LE/ha का छिड़काव',
    organicEn:'Spray NPV (Nuclear Polyhedrosis Virus) @ 250 LE/ha',
    chemicalHi:'इमामेक्टिन बेंज़ोएट 5SG @ 0.4g/L या क्लोरेंट्रानिलिप्रोल 18.5SC @ 0.3ml/L',
    chemicalEn:'Emamectin Benzoate 5SG @ 0.4g/L or Chlorantraniliprole 18.5SC @ 0.3ml/L' },
  { id:'whitefly', nameHi:'सफ़ेद मक्खी', nameEn:'Whitefly', type:'pest', cropId:'cotton', cropEmoji:'🤍', cropHi:'कपास',
    symptomsHi:'पत्तियाँ पीली, चिपचिपी, वायरस फैलाव, पत्तियों के नीचे सफ़ेद कीट',
    symptomsEn:'Yellow sticky leaves, virus spread, white insects under leaves',
    preventionHi:'पीले चिपचिपे ट्रैप, प्रतिरोधी किस्में, अंतरफसल',
    preventionEn:'Yellow sticky traps, resistant varieties, intercropping',
    organicHi:'नीम तेल 5ml/L + साबुन 2ml/L का छिड़काव',
    organicEn:'Spray neem oil 5ml/L + soap 2ml/L',
    chemicalHi:'एसिटामिप्रिड 20SP @ 0.2g/L या स्पाइरोमेसिफेन 22.9SC @ 1ml/L',
    chemicalEn:'Acetamiprid 20SP @ 0.2g/L or Spiromesifen 22.9SC @ 1ml/L' },
  { id:'earlyblight', nameHi:'अगेती झुलसा', nameEn:'Early Blight', type:'fungal', cropId:'tomato', cropEmoji:'🍅', cropHi:'टमाटर',
    symptomsHi:'पत्तियों पर भूरे धब्बे, पीले घेरे, पत्तियाँ नीचे से झड़ना',
    symptomsEn:'Brown spots on leaves with yellow halos, leaves dropping from bottom',
    preventionHi:'फसल चक्र, पत्तियाँ गीली न रखें, उचित दूरी',
    preventionEn:'Crop rotation, avoid wet leaves, proper spacing',
    organicHi:'बेकिंग सोडा 5g/L + नीम तेल 5ml/L का छिड़काव',
    organicEn:'Spray baking soda 5g/L + neem oil 5ml/L',
    chemicalHi:'मैंकोज़ेब 75WP @ 2.5g/L या क्लोरोथैलोनिल 75WP @ 2g/L',
    chemicalEn:'Mancozeb 75WP @ 2.5g/L or Chlorothalonil 75WP @ 2g/L' },
  { id:'fruitborer', nameHi:'फल छेदक', nameEn:'Fruit Borer', type:'pest', cropId:'tomato', cropEmoji:'🍅', cropHi:'टमाटर',
    symptomsHi:'फलों में छेद, अंदर से खाया हुआ, फल सड़ना',
    symptomsEn:'Holes in fruits, eaten from inside, fruit rotting',
    preventionHi:'फेरोमोन ट्रैप, नीम तेल, पक्षी बैठने की जगह',
    preventionEn:'Pheromone traps, neem oil, bird perches',
    organicHi:'Bt (बेसिलस थुरिंजिएंसिस) @ 1g/L का छिड़काव',
    organicEn:'Spray Bt (Bacillus thuringiensis) @ 1g/L',
    chemicalHi:'स्पिनोसैड 45SC @ 0.3ml/L या इंडोक्साकार्ब 14.5SC @ 1ml/L',
    chemicalEn:'Spinosad 45SC @ 0.3ml/L or Indoxacarb 14.5SC @ 1ml/L' },
  { id:'lateblight_tomato', nameHi:'पछेता झुलसा (टमाटर)', nameEn:'Late Blight (Tomato)', type:'fungal', cropId:'tomato', cropEmoji:'🍅', cropHi:'टमाटर',
    symptomsHi:'पत्तियों पर काले-भूरे धब्बे, सफ़ेद फफूंद, फल सड़ना',
    symptomsEn:'Dark brown spots on leaves, white fungus, fruit rot',
    preventionHi:'प्रतिरोधी किस्में, उचित हवा, पत्तियाँ गीली न रखें',
    preventionEn:'Resistant varieties, good air circulation, avoid wet leaves',
    organicHi:'कॉपर सल्फेट 3g/L (बोर्डो मिश्रण) का छिड़काव',
    organicEn:'Spray copper sulphate 3g/L (Bordeaux mixture)',
    chemicalHi:'मेटालैक्सिल + मैंकोज़ेब @ 2.5g/L या साइमोक्सानिल 8% + मैंकोज़ेब 64%',
    chemicalEn:'Metalaxyl + Mancozeb @ 2.5g/L or Cymoxanil 8% + Mancozeb 64%' },
  { id:'purpleblotch', nameHi:'बैंगनी धब्बा', nameEn:'Purple Blotch', type:'fungal', cropId:'onion', cropEmoji:'🧅', cropHi:'प्याज',
    symptomsHi:'पत्तियों पर बैंगनी धब्बे, पत्तियाँ गिरना, कंद सड़ना',
    symptomsEn:'Purple spots on leaves, leaf fall, bulb rotting',
    preventionHi:'बीज उपचार, उचित दूरी, जल निकासी',
    preventionEn:'Seed treatment, proper spacing, good drainage',
    organicHi:'ट्राइकोडर्मा विरिडी @ 5g/L का छिड़काव',
    organicEn:'Spray Trichoderma viride @ 5g/L',
    chemicalHi:'इप्रोडियोन 50WP @ 2g/L या मैंकोज़ेब 75WP @ 2.5g/L',
    chemicalEn:'Iprodione 50WP @ 2g/L or Mancozeb 75WP @ 2.5g/L' },
  { id:'thrips', nameHi:'थ्रिप्स', nameEn:'Thrips', type:'pest', cropId:'onion', cropEmoji:'🧅', cropHi:'प्याज',
    symptomsHi:'पत्तियाँ सिकुड़ना, चाँदी जैसी धारियाँ, पत्तियाँ मुड़ना',
    symptomsEn:'Leaf curling, silver streaks, twisted leaves',
    preventionHi:'नीम तेल, पीले ट्रैप, अंतरफसल',
    preventionEn:'Neem oil, yellow traps, intercropping',
    organicHi:'नीम तेल 5ml/L + साबुन 2ml/L का छिड़काव',
    organicEn:'Spray neem oil 5ml/L + soap 2ml/L',
    chemicalHi:'फिप्रोनिल 5SC @ 1.5ml/L या स्पिनोसैड 45SC @ 0.3ml/L',
    chemicalEn:'Fipronil 5SC @ 1.5ml/L or Spinosad 45SC @ 0.3ml/L' },
  { id:'lateblight', nameHi:'पछेता झुलसा (आलू)', nameEn:'Late Blight (Potato)', type:'fungal', cropId:'potato', cropEmoji:'🥔', cropHi:'आलू',
    symptomsHi:'पत्तियों पर काले धब्बे, सफ़ेद फफूंद, कंद सड़ना',
    symptomsEn:'Black spots on leaves, white fungus, tuber rotting',
    preventionHi:'प्रतिरोधी किस्में, उचित हवा, बीज उपचार',
    preventionEn:'Resistant varieties, good air circulation, seed treatment',
    organicHi:'बोर्डो मिश्रण (कॉपर सल्फेट + चूना) @ 1% का छिड़काव',
    organicEn:'Spray Bordeaux mixture (copper sulphate + lime) @ 1%',
    chemicalHi:'मेटालैक्सिल + मैंकोज़ेब @ 2.5g/L या फेनामिडोन 10% + मैंकोज़ेब 50%',
    chemicalEn:'Metalaxyl + Mancozeb @ 2.5g/L or Fenamidone 10% + Mancozeb 50%' },
  { id:'wilt', nameHi:'उकठा (फ्यूज़ेरियम)', nameEn:'Fusarium Wilt', type:'fungal', cropId:'chickpea', cropEmoji:'🟤', cropHi:'चना',
    symptomsHi:'पौधे अचानक मुरझाना, जड़ें काली, तना काटने पर भूरा रंग',
    symptomsEn:'Sudden wilting, blackened roots, brown color on cutting stem',
    preventionHi:'प्रतिरोधी किस्में, बीज उपचार, फसल चक्र',
    preventionEn:'Resistant varieties, seed treatment, crop rotation',
    organicHi:'ट्राइकोडर्मा विरिडी @ 4g/kg बीज से उपचार',
    organicEn:'Seed treatment with Trichoderma viride @ 4g/kg seed',
    chemicalHi:'कार्बेन्डाज़िम 50WP @ 2g/kg बीज से उपचार',
    chemicalEn:'Seed treatment with Carbendazim 50WP @ 2g/kg seed' },
  { id:'podborer', nameHi:'फली छेदक', nameEn:'Pod Borer', type:'pest', cropId:'chickpea', cropEmoji:'🟤', cropHi:'चना',
    symptomsHi:'फलियों में छेद, दाने खाए हुए, लार्वा फली के अंदर',
    symptomsEn:'Holes in pods, grains eaten, larvae inside pods',
    preventionHi:'फेरोमोन ट्रैप, पक्षी बैठने की जगह, अंतरफसल',
    preventionEn:'Pheromone traps, bird perches, intercropping',
    organicHi:'NPV @ 250 LE/ha या Bt @ 1g/L का छिड़काव',
    organicEn:'Spray NPV @ 250 LE/ha or Bt @ 1g/L',
    chemicalHi:'क्लोरेंट्रानिलिप्रोल 18.5SC @ 0.3ml/L या इंडोक्साकार्ब 14.5SC @ 1ml/L',
    chemicalEn:'Chlorantraniliprole 18.5SC @ 0.3ml/L or Indoxacarb 14.5SC @ 1ml/L' },
  { id:'redrot', nameHi:'लाल सड़न', nameEn:'Red Rot', type:'fungal', cropId:'sugarcane', cropEmoji:'🍬', cropHi:'गन्ना',
    symptomsHi:'तना काटने पर लाल रंग, खट्टी गंध, पत्तियाँ पीली',
    symptomsEn:'Red color on cutting stem, sour smell, yellow leaves',
    preventionHi:'प्रतिरोधी किस्में, स्वस्थ बीज, जल निकासी',
    preventionEn:'Resistant varieties, healthy seed, good drainage',
    organicHi:'ट्राइकोडर्मा हार्ज़ियानम से बीज उपचार',
    organicEn:'Seed treatment with Trichoderma harzianum',
    chemicalHi:'कार्बेन्डाज़िम 50WP @ 1g/L से बीज उपचार, रोगी पौधे हटाएं',
    chemicalEn:'Seed treatment with Carbendazim 50WP @ 1g/L, remove infected plants' },
  { id:'mustard_aphid', nameHi:'माहू (चेंपा)', nameEn:'Aphid', type:'pest', cropId:'mustard', cropEmoji:'🌼', cropHi:'सरसों',
    symptomsHi:'पत्तियाँ मुड़ना, चिपचिपा पदार्थ, पौधे कमज़ोर',
    symptomsEn:'Leaf curling, sticky substance, weakened plants',
    preventionHi:'नीम तेल, प्राकृतिक शत्रु (लेडीबर्ड), पीले ट्रैप',
    preventionEn:'Neem oil, natural predators (ladybird), yellow traps',
    organicHi:'नीम तेल 5ml/L + साबुन 2ml/L का छिड़काव',
    organicEn:'Spray neem oil 5ml/L + soap 2ml/L',
    chemicalHi:'डाइमेथोएट 30EC @ 1.5ml/L या थायमेथोक्सम 25WG @ 0.3g/L',
    chemicalEn:'Dimethoate 30EC @ 1.5ml/L or Thiamethoxam 25WG @ 0.3g/L' },
  { id:'whiterust', nameHi:'सफ़ेद रतुआ', nameEn:'White Rust', type:'fungal', cropId:'mustard', cropEmoji:'🌼', cropHi:'सरसों',
    symptomsHi:'पत्तियों पर सफ़ेद छाले, पत्तियाँ मुड़ना, फूल विकृत',
    symptomsEn:'White blisters on leaves, leaf curling, distorted flowers',
    preventionHi:'प्रतिरोधी किस्में, उचित दूरी, बीज उपचार',
    preventionEn:'Resistant varieties, proper spacing, seed treatment',
    organicHi:'कॉपर ऑक्सीक्लोराइड 50WP @ 3g/L का छिड़काव',
    organicEn:'Spray copper oxychloride 50WP @ 3g/L',
    chemicalHi:'मेटालैक्सिल + मैंकोज़ेब @ 2.5g/L या रिडोमिल गोल्ड',
    chemicalEn:'Metalaxyl + Mancozeb @ 2.5g/L or Ridomil Gold' },
  { id:'powderymildew', nameHi:'चूर्णिल आसिता', nameEn:'Powdery Mildew', type:'fungal', cropId:'mango', cropEmoji:'🥭', cropHi:'आम',
    symptomsHi:'पत्तियों पर सफ़ेद पाउडर, फूल झड़ना, फल नहीं बनते',
    symptomsEn:'White powder on leaves, flower drop, no fruit formation',
    preventionHi:'उचित छंटाई, हवा का प्रवाह, नमी कम रखें',
    preventionEn:'Proper pruning, good air flow, reduce humidity',
    organicHi:'बेकिंग सोडा 5g/L + नीम तेल 5ml/L का छिड़काव',
    organicEn:'Spray baking soda 5g/L + neem oil 5ml/L',
    chemicalHi:'सल्फर 80WP @ 3g/L या हेक्साकोनाज़ोल 5EC @ 1ml/L',
    chemicalEn:'Sulphur 80WP @ 3g/L or Hexaconazole 5EC @ 1ml/L' },
  { id:'leafcurl', nameHi:'पत्ती मोड़क विषाणु', nameEn:'Leaf Curl Virus', type:'viral', cropId:'chilli', cropEmoji:'🌶️', cropHi:'मिर्च',
    symptomsHi:'पत्तियाँ मुड़ना, पौधे बौने, फल कम बनते हैं',
    symptomsEn:'Leaf curling, stunted plants, reduced fruit set',
    preventionHi:'थ्रिप्स नियंत्रण, प्रतिरोधी किस्में, रोगी पौधे हटाएं',
    preventionEn:'Thrips control, resistant varieties, remove infected plants',
    organicHi:'नीम तेल 5ml/L का छिड़काव, थ्रिप्स नियंत्रण के लिए पीले ट्रैप',
    organicEn:'Spray neem oil 5ml/L, yellow traps for thrips control',
    chemicalHi:'वायरस का कोई इलाज नहीं — थ्रिप्स के लिए इमिडाक्लोप्रिड 17.8SL @ 0.3ml/L',
    chemicalEn:'No cure for virus — for thrips: Imidacloprid 17.8SL @ 0.3ml/L' },
  { id:'panamawilt', nameHi:'पनामा विल्ट', nameEn:'Panama Wilt', type:'fungal', cropId:'banana', cropEmoji:'🍌', cropHi:'केला',
    symptomsHi:'पत्तियाँ पीली, तना काटने पर भूरा, पौधे मर जाते हैं',
    symptomsEn:'Yellow leaves, brown on cutting stem, plants die',
    preventionHi:'प्रतिरोधी किस्में (Cavendish), स्वस्थ पौध, मिट्टी उपचार',
    preventionEn:'Resistant varieties (Cavendish), healthy seedlings, soil treatment',
    organicHi:'ट्राइकोडर्मा विरिडी से मिट्टी उपचार, रोगी पौधे हटाएं',
    organicEn:'Soil treatment with Trichoderma viride, remove infected plants',
    chemicalHi:'कोई प्रभावी रासायनिक उपचार नहीं — रोकथाम ही उपाय है',
    chemicalEn:'No effective chemical treatment — prevention is the only solution' },
  { id:'rhizomerot', nameHi:'प्रकंद सड़न', nameEn:'Rhizome Rot', type:'fungal', cropId:'turmeric', cropEmoji:'🟡', cropHi:'हल्दी',
    symptomsHi:'पत्तियाँ पीली, प्रकंद सड़ना, पौधे मुरझाना',
    symptomsEn:'Yellow leaves, rhizome rotting, plants wilting',
    preventionHi:'जल निकासी, बीज उपचार, फसल चक्र',
    preventionEn:'Good drainage, seed treatment, crop rotation',
    organicHi:'ट्राइकोडर्मा हार्ज़ियानम @ 4g/kg बीज से उपचार',
    organicEn:'Seed treatment with Trichoderma harzianum @ 4g/kg seed',
    chemicalHi:'मेटालैक्सिल + मैंकोज़ेब @ 2.5g/L से बीज उपचार',
    chemicalEn:'Seed treatment with Metalaxyl + Mancozeb @ 2.5g/L' },
  { id:'downy_mildew', nameHi:'मृदुरोमिल आसिता', nameEn:'Downy Mildew', type:'fungal', cropId:'maize', cropEmoji:'🌽', cropHi:'मक्का',
    symptomsHi:'पत्तियों पर पीली धारियाँ, नीचे सफ़ेद फफूंद, पौधे बौने',
    symptomsEn:'Yellow stripes on leaves, white fungus below, stunted plants',
    preventionHi:'प्रतिरोधी किस्में, बीज उपचार, जल निकासी',
    preventionEn:'Resistant varieties, seed treatment, good drainage',
    organicHi:'कॉपर ऑक्सीक्लोराइड 50WP @ 3g/L का छिड़काव',
    organicEn:'Spray copper oxychloride 50WP @ 3g/L',
    chemicalHi:'मेटालैक्सिल 35SD @ 6g/kg बीज से उपचार',
    chemicalEn:'Seed treatment with Metalaxyl 35SD @ 6g/kg seed' },
  { id:'stem_borer', nameHi:'तना छेदक', nameEn:'Stem Borer', type:'pest', cropId:'maize', cropEmoji:'🌽', cropHi:'मक्का',
    symptomsHi:'तने में छेद, "डेड हार्ट", पत्तियाँ मुरझाना',
    symptomsEn:'Holes in stem, dead heart, wilting leaves',
    preventionHi:'समय पर बुवाई, फसल अवशेष नष्ट करें',
    preventionEn:'Timely sowing, destroy crop residues',
    organicHi:'ट्राइकोग्रामा परजीवी @ 50,000/ha छोड़ें',
    organicEn:'Release Trichogramma parasitoid @ 50,000/ha',
    chemicalHi:'कार्बोफ्यूरान 3G @ 20kg/ha या क्लोरपाइरीफॉस 20EC @ 2.5ml/L',
    chemicalEn:'Carbofuran 3G @ 20kg/ha or Chlorpyrifos 20EC @ 2.5ml/L' },
  { id:'bacterial_blight', nameHi:'जीवाणु झुलसा', nameEn:'Bacterial Blight', type:'bacterial', cropId:'rice', cropEmoji:'🌾', cropHi:'धान',
    symptomsHi:'पत्तियों के किनारे पीले-भूरे, पत्तियाँ सूखना, दूधिया रिसाव',
    symptomsEn:'Yellow-brown leaf margins, leaf drying, milky ooze',
    preventionHi:'प्रतिरोधी किस्में, बीज उपचार, संतुलित नाइट्रोजन',
    preventionEn:'Resistant varieties, seed treatment, balanced nitrogen',
    organicHi:'कॉपर ऑक्सीक्लोराइड 50WP @ 3g/L का छिड़काव',
    organicEn:'Spray copper oxychloride 50WP @ 3g/L',
    chemicalHi:'स्ट्रेप्टोमाइसिन सल्फेट + टेट्रासाइक्लिन @ 0.5g/L',
    chemicalEn:'Streptomycin sulphate + Tetracycline @ 0.5g/L' },
  { id:'mosaic_virus', nameHi:'मोज़ेक विषाणु', nameEn:'Mosaic Virus', type:'viral', cropId:'soybean', cropEmoji:'🫘', cropHi:'सोयाबीन',
    symptomsHi:'पत्तियों पर हरे-पीले धब्बे, पत्तियाँ सिकुड़ना, उपज कम',
    symptomsEn:'Green-yellow mosaic on leaves, leaf puckering, reduced yield',
    preventionHi:'प्रतिरोधी किस्में, माहू नियंत्रण, रोगी पौधे हटाएं',
    preventionEn:'Resistant varieties, aphid control, remove infected plants',
    organicHi:'नीम तेल 5ml/L का छिड़काव माहू नियंत्रण के लिए',
    organicEn:'Spray neem oil 5ml/L for aphid control',
    chemicalHi:'वायरस का कोई इलाज नहीं — माहू के लिए डाइमेथोएट 30EC @ 1.5ml/L',
    chemicalEn:'No cure for virus — for aphids: Dimethoate 30EC @ 1.5ml/L' },
  { id:'tikka_disease', nameHi:'टिक्का रोग', nameEn:'Tikka Disease', type:'fungal', cropId:'groundnut', cropEmoji:'🥜', cropHi:'मूँगफली',
    symptomsHi:'पत्तियों पर भूरे गोल धब्बे, पत्तियाँ झड़ना, उपज कम',
    symptomsEn:'Brown circular spots on leaves, defoliation, reduced yield',
    preventionHi:'फसल चक्र, प्रतिरोधी किस्में, उचित दूरी',
    preventionEn:'Crop rotation, resistant varieties, proper spacing',
    organicHi:'कॉपर ऑक्सीक्लोराइड 50WP @ 3g/L का छिड़काव',
    organicEn:'Spray copper oxychloride 50WP @ 3g/L',
    chemicalHi:'क्लोरोथैलोनिल 75WP @ 2g/L या मैंकोज़ेब 75WP @ 2.5g/L',
    chemicalEn:'Chlorothalonil 75WP @ 2g/L or Mancozeb 75WP @ 2.5g/L' },
  { id:'sooty_mould', nameHi:'काली फफूंद', nameEn:'Sooty Mould', type:'fungal', cropId:'mango', cropEmoji:'🥭', cropHi:'आम',
    symptomsHi:'पत्तियों पर काली परत, फल काले, प्रकाश संश्लेषण कम',
    symptomsEn:'Black coating on leaves, black fruits, reduced photosynthesis',
    preventionHi:'माहू और मिलीबग नियंत्रण, उचित छंटाई',
    preventionEn:'Control aphids and mealybugs, proper pruning',
    organicHi:'नीम तेल 5ml/L + साबुन 2ml/L से धोएं',
    organicEn:'Wash with neem oil 5ml/L + soap 2ml/L',
    chemicalHi:'कॉपर ऑक्सीक्लोराइड 50WP @ 3g/L का छिड़काव',
    chemicalEn:'Spray copper oxychloride 50WP @ 3g/L' },
  { id:'crown_rot', nameHi:'मुकुट सड़न', nameEn:'Crown Rot', type:'fungal', cropId:'groundnut', cropEmoji:'🥜', cropHi:'मूँगफली',
    symptomsHi:'पौधे का आधार काला, पत्तियाँ पीली, पौधे मर जाते हैं',
    symptomsEn:'Black base of plant, yellow leaves, plants die',
    preventionHi:'बीज उपचार, जल निकासी, फसल चक्र',
    preventionEn:'Seed treatment, good drainage, crop rotation',
    organicHi:'ट्राइकोडर्मा विरिडी @ 4g/kg बीज से उपचार',
    organicEn:'Seed treatment with Trichoderma viride @ 4g/kg seed',
    chemicalHi:'थायरम 75WP @ 3g/kg बीज से उपचार',
    chemicalEn:'Seed treatment with Thiram 75WP @ 3g/kg seed' },
];

export function getDiseasesByType(type: Disease['type']) {
  return DISEASES.filter(d => d.type === type);
}

export function getDiseasesByCrop(cropId: string) {
  return DISEASES.filter(d => d.cropId === cropId);
}
